### ISSUE TITLE
Meta Issue: New and Improved Example Gallery

### ISSUE THREAD

**Issue by nshahan** [dart-lang/angular_components_example#9]
As more components are added the examples page is becoming unwieldy. Need a new example gallery.

- [ ] Each component examples in unique files
- [ ] Better organization (search?)
- [ ] Links to source code
- [ ] Embed documentation

**Comment by jimmyff** [comment]
+1

I just came on here to file an issue suggesting this. Would be great to have individual examples of `material-dropdown-select` etc

**Comment by adaojunior** [comment]
Would the dart-team accept a PR with the improvements ?

**Comment by tsander** [comment]
We actually already have one, but we need to make it work externally. Watch this space we are working on it.

**Comment by adaojunior** [comment]
Nice to hear

**Comment by nshahan** [comment]
Open sourced the internal gallery with these features in #61.
